### ISSUE TITLE
some question about function "get_user_vertor"

### ISSUE THREAD

**Issue by ZYM6-6** [Studenthc/CRIF#2]
Hello, I'm very interested in your paper. But the “get_user_vertor” function in the convhis.py file is unclear. Why need user_ID to divide by the total number of projects?

**Comment by LSunQQ** [comment]
We may have accidentally written it wrong and corrected it, but the order of magnitude of user and item is the same for each of the four datasets, and the result of function str() is the same and does not affect the result.
